var sections = {'pages': [
     {'title': 'Overview', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#overview'},
     {'title': 'Colors', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#colors'},
     {'title': 'Logos', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#logos'},
     {'title': 'Maps', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#maps'},
     {'title': 'Banners', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#banners'},
     {'title': 'Responsive', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#responsive'},
     {'title': 'Containers', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#containers'},
     {'title': 'Media Queries', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#mediaqueries'},
     {'title': 'Visibility', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#visibility'},
     {'title': 'Typography', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#typography'},
     {'title': 'Fonts', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#fonts'},
     {'title': 'Iconography', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#iconography'},
     {'title': 'Formatting', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#formatting'},
     {'title': 'Media', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#media'},
     {'title': 'Product Images', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#productimages'},
     {'title': 'Thumbnails', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#thumbnails'},
     {'title': 'Videos', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#videos'},
     {'title': '360 Photos', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#360photos'},
     {'title': 'HTML Elements', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#html'},
     {'title': 'Lists', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#lists'},
     {'title': 'Tables', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#tables'},
     {'title': 'Links & Downloads', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#linksdownloads'},
     {'title': 'Inputs', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#inputs'},
     {'title': 'Text Areas', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#textareas'},
     {'title': 'Forms', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#forms'},
     {'title': 'Labels', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#labels'},
     {'title': 'Buttons', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#buttons'},
     {'title': 'Interactions', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#interactions'},
     {'title': 'Animations', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#animations'},
     {'title': 'Slideshows', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#slideshows'},
     {'title': 'Modals', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#modals'},
     {'title': 'LightBoxes', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#lightboxes'},
     {'title': 'Dropdowns', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#dropdowns'},
     {'title': 'Tooltips', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#tooltips'},
     {'title': 'Switches', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#switches'},
     {'title': 'Breadcrumbs', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#breadcrumbs'},
     {'title': 'Pagination', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#pagination'},
     {'title': 'Range Sliders', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#rangesliders'},
     {'title': 'Alerts & Warnings', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#alertswarnings'},
     {'title': 'Progress Bars', 'thumb': 'img/search.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#progressbars'},
     {'title': 'Accordions', 'thumb': 'img/drop.png', 'text': 'Description', 'tags': 'tagshere', 'loc': '#accordions'},
     {'title': 'Tabs', 'thumb': 'img/tipr.png', 'text': 'Description', 'tags': 'Tipue', 'loc': '#tabs'}
]};
